# Night City Mix — kitty
foreground            #beccd9
background            #0c1a1e
selection_foreground  #0c1a1e
selection_background  #22abbd
cursor                #1fc4c6
cursor_text_color     #0c1a1e
url_color             #1fc4c6
active_border_color   #22abbd
inactive_border_color #2a3a40
active_tab_foreground   #0c1a1e
active_tab_background    #ffd05d
inactive_tab_foreground #beccd9
inactive_tab_background #0c1a1e
color0 #0c1a1e
color1 #f9646a
color2 #12ba7b
color3 #ffd05d
color4 #4189c4
color5 #b858ca
color6 #22abbd
color7 #beccd9
color8  #2a3a40
color9  #ff8a80
color10 #1fc4c6
color11 #ffe08a
color12 #5fa0d8
color13 #d44cbd
color14 #4fd8d8
color15 #dce6ee
