-- Night City Mix — WezTerm (generated by scripts/blend.py)
-- return this from your config, or merge into config.colors.
return {
  foreground = "#b6c5d3",
  background = "#101a1f",
  cursor_bg = "#0cc7c2",
  cursor_fg = "#101a1f",
  cursor_border = "#0cc7c2",
  selection_fg = "#101a1f",
  selection_bg = "#2bbcd5",
  scrollbar_thumb = "#2c3d4b",
  split = "#2bbcd5",
  ansi = {
    "#0d151d", -- black
    "#f65162", -- red
    "#49d575", -- green
    "#f2c74b", -- yellow
    "#4486d5", -- blue
    "#e446bc", -- magenta
    "#2dcad8", -- cyan
    "#b8c6d7", -- white
  },
  brights = {
    "#2b3851", -- bright black
    "#fa70a7", -- bright red
    "#4deda4", -- bright green
    "#f9dc6d", -- bright yellow
    "#6fa1ec", -- bright blue
    "#ed7dde", -- bright magenta
    "#5bf4f1", -- bright cyan
    "#e2e9f4", -- bright white
  },
  tab_bar = {
    background = "#0c1217",
    active_tab   = { bg_color = "#f2c74b", fg_color = "#101a1f" },
    inactive_tab = { bg_color = "#15242d", fg_color = "#b6c5d3" },
  },
}
