# Box UK Contrast — kitty
foreground            #b8c7cc
background            #161e22
selection_foreground  #161e22
selection_background  #017c9d
cursor                #15b8ae
cursor_text_color     #161e22
url_color             #15b8ae
active_border_color   #017c9d
inactive_border_color #303b47
active_tab_foreground   #161e22
active_tab_background    #ffcb6e
inactive_tab_foreground #b8c7cc
inactive_tab_background #161e22
color0 #161e22
color1 #f77669
color2 #019d76
color3 #ffcb6e
color4 #017c9d
color5 #b750ae
color6 #15b8ae
color7 #b8c7cc
color8  #303b47
color9  #ff8a80
color10 #15b8ae
color11 #ffd68a
color12 #2f9dc0
color13 #c77dbf
color14 #4fd8ce
color15 #e6e6e6
