# Solarized Osaka — kitty
foreground            #839495
background            #00141a
selection_foreground  #00141a
selection_background  #2aa298
cursor                #15b8ae
cursor_text_color     #00141a
url_color             #15b8ae
active_border_color   #2aa298
inactive_border_color #22464f
active_tab_foreground   #00141a
active_tab_background    #b28600
inactive_tab_foreground #839495
inactive_tab_background #00141a
color0 #00141a
color1 #dc312e
color2 #859900
color3 #b28600
color4 #2f879d
color5 #d33682
color6 #2aa298
color7 #839495
color8  #22464f
color9  #ca4c16
color10 #15b8ae
color11 #b28600
color12 #5a8c9e
color13 #9c7fd2
color14 #4fd1c5
color15 #a6b6b6
