#!/usr/bin/env python3
"""Generate Night City Mix by blending the three source palettes.

Box UK brings the calm grounds, Solarized Osaka the structure, Lucy the neon
pop — expressed as per-section weights. Blending happens in linear RGB
(gamma-correct), so midpoints don't go muddy the way naive hex averaging does.

Usage: python3 scripts/blend.py   (rewrites palettes/night-city-mix.json;
run scripts/generate.py afterwards to refresh extras/)
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES = ["box-uk-contrast", "solarized-osaka", "cyberpunk-lucy"]

# (box-uk, osaka, lucy) weights per section
WEIGHTS = {
    "background": (0.60, 0.25, 0.15),  # calm grounds win
    "foreground": (0.40, 0.20, 0.40),
    "accents":    (0.30, 0.20, 0.50),  # neon pop wins
    "ansi":       (0.30, 0.20, 0.50),
}
BRIGHT_WEIGHTS = (0.20, 0.10, 0.70)    # brights lean hardest into Lucy


def srgb_to_linear(c):
    c /= 255.0
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def linear_to_srgb(c):
    c = 12.92 * c if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055
    return max(0, min(255, round(c * 255)))


def blend(hexes, weights):
    total = sum(w for h, w in zip(hexes, weights) if h)
    out = []
    for i in (1, 3, 5):
        acc = 0.0
        for h, w in zip(hexes, weights):
            if h:
                acc += (w / total) * srgb_to_linear(int(h[i:i + 2], 16))
        out.append(linear_to_srgb(acc))
    return "#{:02x}{:02x}{:02x}".format(*out)


palettes = [json.loads((ROOT / "palettes" / f"{n}.json").read_text()) for n in SOURCES]

mix: dict = {
    "name": "Night City Mix",
    "family": "Blend (Box UK × Solarized Osaka × Lucy)",
    "source": "Generated by scripts/blend.py — gamma-correct weighted blend of the other three palettes",
}
for section, weights in WEIGHTS.items():
    keys = []
    for p in palettes:
        for k in p[section]:
            if k not in keys:
                keys.append(k)
    mix[section] = {}
    for k in keys:
        w = BRIGHT_WEIGHTS if section == "ansi" and k.startswith("bright_") else weights
        mix[section][k] = blend([p[section].get(k) for p in palettes], w)

# accents.blue isn't in any source accent set; take it from the ansi blend
mix["accents"].setdefault("blue", mix["ansi"]["blue"])

(ROOT / "palettes" / "night-city-mix.json").write_text(json.dumps(mix, indent=2, ensure_ascii=False) + "\n")

print("night-city-mix.json regenerated:")
print("  bg:", mix["background"]["bg"], " fg:", mix["foreground"]["fg"])
for k, v in mix["accents"].items():
    print(f"  {k:<8} {v}")
print("now run: python3 scripts/generate.py")
