#!/usr/bin/env python3
"""Generate Night City Mix by blending the three source palettes.

Box UK brings the calm grounds, Solarized Osaka the structure, Lucy the neon
pop — expressed as per-section weights. Blending happens in linear RGB
(gamma-correct), so midpoints don't go muddy the way naive hex averaging does.

Usage: python3 scripts/blend.py   (from the repo root; rewrites
palettes/night-city-mix.json and themes/night-city-mix/*)
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES = ["box-uk-contrast", "solarized-osaka", "cyberpunk-lucy"]

# (box-uk, osaka, lucy) weights per section
WEIGHTS = {
    "background": (0.60, 0.25, 0.15),  # calm grounds win
    "foreground": (0.40, 0.20, 0.40),
    "accents":    (0.30, 0.20, 0.50),  # neon pop wins
    "ansi":       (0.30, 0.20, 0.50),
}
BRIGHT_WEIGHTS = (0.20, 0.10, 0.70)    # brights lean hardest into Lucy


def srgb_to_linear(c):
    c /= 255.0
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def linear_to_srgb(c):
    c = 12.92 * c if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055
    return max(0, min(255, round(c * 255)))


def blend(hexes, weights):
    total = sum(w for h, w in zip(hexes, weights) if h)
    out = []
    for i in (1, 3, 5):
        acc = 0.0
        for h, w in zip(hexes, weights):
            if h:
                acc += (w / total) * srgb_to_linear(int(h[i:i + 2], 16))
        out.append(linear_to_srgb(acc))
    return "#{:02x}{:02x}{:02x}".format(*out)


palettes = [json.loads((ROOT / "palettes" / f"{n}.json").read_text()) for n in SOURCES]

mix: dict = {
    "name": "Night City Mix",
    "family": "Blend (Box UK × Solarized Osaka × Lucy)",
    "source": "Generated by scripts/blend.py — gamma-correct weighted blend of the other three palettes",
}
for section, weights in WEIGHTS.items():
    keys = []
    for p in palettes:
        for k in p[section]:
            if k not in keys:
                keys.append(k)
    mix[section] = {}
    for k in keys:
        w = BRIGHT_WEIGHTS if section == "ansi" and k.startswith("bright_") else weights
        mix[section][k] = blend([p[section].get(k) for p in palettes], w)

# accents.blue isn't in any source accent set; take it from the ansi blend
mix["accents"].setdefault("blue", mix["ansi"]["blue"])

(ROOT / "palettes" / "night-city-mix.json").write_text(json.dumps(mix, indent=2, ensure_ascii=False) + "\n")

# ---- theme files -----------------------------------------------------------
bg, fg = mix["background"], mix["foreground"]
ac, ansi = mix["accents"], mix["ansi"]
ANSI_ORDER = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
norm = [ansi[k] for k in ANSI_ORDER]
bright = [ansi["bright_" + k] for k in ANSI_ORDER]
tdir = ROOT / "themes" / "night-city-mix"

tdir.joinpath("kitty.conf").write_text(
    "# Night City Mix — kitty (generated by scripts/blend.py)\n"
    f"foreground            {fg['fg']}\nbackground            {bg['bg']}\n"
    f"selection_foreground  {bg['bg']}\nselection_background  {ac['cyan']}\n"
    f"cursor                {ac['teal']}\ncursor_text_color     {bg['bg']}\n"
    f"url_color             {ac['teal']}\n"
    f"active_border_color   {ac['cyan']}\ninactive_border_color {bg['overlay']}\n"
    f"active_tab_foreground   {bg['bg']}\nactive_tab_background    {ac['yellow']}\n"
    f"inactive_tab_foreground {fg['fg']}\ninactive_tab_background {bg['bg']}\n"
    + "".join(f"color{i} {c}\n" for i, c in enumerate(norm + bright))
)

tdir.joinpath("ghostty").write_text(
    "# Night City Mix — Ghostty (generated by scripts/blend.py)\n"
    f"background = {bg['bg'][1:]}\nforeground = {fg['fg'][1:]}\n"
    f"cursor-color = {ac['teal'][1:]}\n"
    f"selection-background = {ac['cyan'][1:]}\nselection-foreground = {bg['bg'][1:]}\n"
    + "".join(f"palette = {i}={c}\n" for i, c in enumerate(norm + bright))
)

tdir.joinpath("alacritty.toml").write_text(
    "# Night City Mix — Alacritty (generated by scripts/blend.py)\n"
    "[colors.primary]\n"
    f'background = "{bg["bg"]}"\nforeground = "{fg["fg"]}"\n'
    "[colors.cursor]\n"
    f'text   = "{bg["bg"]}"\ncursor = "{ac["teal"]}"\n'
    "[colors.selection]\n"
    f'text       = "{bg["bg"]}"\nbackground = "{ac["cyan"]}"\n'
    "[colors.normal]\n"
    + "".join(f'{k:<7} = "{c}"\n' for k, c in zip(ANSI_ORDER, norm))
    + "[colors.bright]\n"
    + "".join(f'{k:<7} = "{c}"\n' for k, c in zip(ANSI_ORDER, bright))
)

tdir.joinpath("wezterm.lua").write_text(
    "-- Night City Mix — WezTerm (generated by scripts/blend.py)\n"
    "-- return this from your config, or merge into config.colors.\n"
    "return {\n"
    f'  foreground = "{fg["fg"]}",\n  background = "{bg["bg"]}",\n'
    f'  cursor_bg = "{ac["teal"]}",\n  cursor_fg = "{bg["bg"]}",\n  cursor_border = "{ac["teal"]}",\n'
    f'  selection_fg = "{bg["bg"]}",\n  selection_bg = "{ac["cyan"]}",\n'
    f'  scrollbar_thumb = "{bg["overlay"]}",\n  split = "{ac["cyan"]}",\n'
    "  ansi = {\n" + "".join(f'    "{c}", -- {k}\n' for k, c in zip(ANSI_ORDER, norm)) + "  },\n"
    "  brights = {\n" + "".join(f'    "{c}", -- bright {k}\n' for k, c in zip(ANSI_ORDER, bright)) + "  },\n"
    "  tab_bar = {\n"
    f'    background = "{bg["bg_dark"]}",\n'
    f'    active_tab   = {{ bg_color = "{ac["yellow"]}", fg_color = "{bg["bg"]}" }},\n'
    f'    inactive_tab = {{ bg_color = "{bg["bg_highlight"]}", fg_color = "{fg["fg"]}" }},\n'
    "  },\n}\n"
)

print("night-city-mix regenerated:")
print("  bg:", bg["bg"], " fg:", fg["fg"])
for k, v in ac.items():
    print(f"  {k:<8} {v}")
