#!/usr/bin/env python3
"""Render extras/<app>/<palette>.<ext> for every palette JSON.

tokyonight/solarized-osaka-style layout: themes are grouped by app, and every
generated file comes from the JSON single-source-of-truth in palettes/.

Usage: python3 scripts/generate.py   (from anywhere; paths are repo-relative)
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ANSI_ORDER = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]


def render(p):
    name = p["name"]
    bg, fg, ac, ansi = p["background"], p["foreground"], p["accents"], p["ansi"]
    norm = [ansi[k] for k in ANSI_ORDER]
    bright = [ansi["bright_" + k] for k in ANSI_ORDER]

    kitty = (
        f"# {name} — kitty (generated by scripts/generate.py)\n"
        f"foreground            {fg['fg']}\nbackground            {bg['bg']}\n"
        f"selection_foreground  {bg['bg']}\nselection_background  {ac['cyan']}\n"
        f"cursor                {ac['teal']}\ncursor_text_color     {bg['bg']}\n"
        f"url_color             {ac['teal']}\n"
        f"active_border_color   {ac['cyan']}\ninactive_border_color {bg['overlay']}\n"
        f"active_tab_foreground   {bg['bg']}\nactive_tab_background    {ac['yellow']}\n"
        f"inactive_tab_foreground {fg['fg']}\ninactive_tab_background {bg['bg']}\n"
        + "".join(f"color{i} {c}\n" for i, c in enumerate(norm + bright))
    )

    ghostty = (
        f"# {name} — Ghostty (generated by scripts/generate.py)\n"
        f"background = {bg['bg'][1:]}\nforeground = {fg['fg'][1:]}\n"
        f"cursor-color = {ac['teal'][1:]}\ncursor-text = {bg['bg'][1:]}\n"
        f"selection-background = {ac['cyan'][1:]}\nselection-foreground = {bg['bg'][1:]}\n"
        + "".join(f"palette = {i}={c}\n" for i, c in enumerate(norm + bright))
    )

    alacritty = (
        f"# {name} — Alacritty (generated by scripts/generate.py)\n"
        "[colors.primary]\n"
        f'background = "{bg["bg"]}"\nforeground = "{fg["fg"]}"\n'
        "[colors.cursor]\n"
        f'text   = "{bg["bg"]}"\ncursor = "{ac["teal"]}"\n'
        "[colors.selection]\n"
        f'text       = "{bg["bg"]}"\nbackground = "{ac["cyan"]}"\n'
        "[colors.normal]\n"
        + "".join(f'{k:<7} = "{c}"\n' for k, c in zip(ANSI_ORDER, norm))
        + "[colors.bright]\n"
        + "".join(f'{k:<7} = "{c}"\n' for k, c in zip(ANSI_ORDER, bright))
    )

    wezterm = (
        f"-- {name} — WezTerm (generated by scripts/generate.py)\n"
        "-- return this from your config, or merge into config.colors.\n"
        "return {\n"
        f'  foreground = "{fg["fg"]}",\n  background = "{bg["bg"]}",\n'
        f'  cursor_bg = "{ac["teal"]}",\n  cursor_fg = "{bg["bg"]}",\n  cursor_border = "{ac["teal"]}",\n'
        f'  selection_fg = "{bg["bg"]}",\n  selection_bg = "{ac["cyan"]}",\n'
        f'  scrollbar_thumb = "{bg["overlay"]}",\n  split = "{ac["cyan"]}",\n'
        "  ansi = {\n" + "".join(f'    "{c}", -- {k}\n' for k, c in zip(ANSI_ORDER, norm)) + "  },\n"
        "  brights = {\n" + "".join(f'    "{c}", -- bright {k}\n' for k, c in zip(ANSI_ORDER, bright)) + "  },\n"
        "  tab_bar = {\n"
        f'    background = "{bg["bg_dark"]}",\n'
        f'    active_tab   = {{ bg_color = "{ac["yellow"]}", fg_color = "{bg["bg"]}" }},\n'
        f'    inactive_tab = {{ bg_color = "{bg["bg_highlight"]}", fg_color = "{fg["fg"]}" }},\n'
        "  },\n}\n"
    )

    tmux = (
        f"# {name} — tmux (generated by scripts/generate.py)\n"
        f'set -g mode-style "fg={bg["bg"]},bg={ac["cyan"]}"\n'
        f'set -g message-style "fg={fg["fg"]},bg={bg["bg_highlight"]}"\n'
        f'set -g message-command-style "fg={fg["fg"]},bg={bg["bg_highlight"]}"\n'
        f'set -g pane-border-style "fg={bg["overlay"]}"\n'
        f'set -g pane-active-border-style "fg={ac["cyan"]}"\n'
        "set -g status-position bottom\n"
        f'set -g status-style "fg={ac["cyan"]},bg={bg["bg_dark"]}"\n'
        f'set -g status-left "#[fg={bg["bg"]},bg={ac["cyan"]},bold] #S #[fg={ac["cyan"]},bg={bg["bg_dark"]}]"\n'
        f'set -g status-right "#[fg={fg["fg_dim"]}] %H:%M #[fg={bg["bg"]},bg={ac["teal"]},bold] #h "\n'
        f'setw -g window-status-style "fg={fg["fg_dim"]},bg={bg["bg_dark"]}"\n'
        f'setw -g window-status-format " #I #W "\n'
        f'setw -g window-status-current-style "fg={bg["bg"]},bg={ac["teal"]},bold"\n'
        f'setw -g window-status-current-format " #I #W "\n'
        f'setw -g window-status-activity-style "fg={ac["yellow"]},bg={bg["bg_dark"]}"\n'
    )

    return {
        ("kitty", ".conf"): kitty,
        ("ghostty", ""): ghostty,
        ("alacritty", ".toml"): alacritty,
        ("wezterm", ".lua"): wezterm,
        ("tmux", ".tmux"): tmux,
    }


for path in sorted((ROOT / "palettes").glob("*.json")):
    palette = json.loads(path.read_text())
    for (app, ext), content in render(palette).items():
        out = ROOT / "extras" / app / (path.stem + ext)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content)
        print(f"  extras/{app}/{path.stem}{ext}")
